apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoupdater
  namespace: openshift-cluster-version
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoupdater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: autoupdater
  namespace: openshift-cluster-version
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: yolo
  namespace: openshift-cluster-version
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Exists
          affinity: {}
          containers:
          - name: yolo
            command:
              - /bin/bash
              - -c
              - |
                #/bin/bash
                die(){
                	echo "${1}"
                	exit "${2}"
                }
                if [ $(oc get clusterversion/version -o jsonpath='{.status.availableUpdates}') != '<nil>' ]; then
                	oc adm upgrade --to-latest || die "Cannot update to latest" 1
                else
                	die "No upgrade available" 0
                fi
            image: registry.redhat.io/openshift4/ose-cli:latest
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
          serviceAccountName: autoupdater
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  schedule: "53 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
